pub const TEAM_MIXIN_USER_ID: &str = "773e5e77-4107-45c2-b648-8fc722ed77f5";

pub const SCP: &str = "PROFILE:READ PROFILE:WRITE PHONE:READ PHONE:WRITE CONTACTS:READ CONTACTS:WRITE MESSAGES:READ MESSAGES:WRITE ASSETS:READ SNAPSHOTS:READ CIRCLES:READ CIRCLES:WRITE STICKERS:READ STICKERS:WRITE";

pub const SCP_FULL: &str = "FULL";
