// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'frb_generated.dart';

part 'api.freezed.dart';

enum ConnectionFailedReason {
  versionNotMatched,
  unknown,
}

@freezed
sealed class DeviceTransferEvent with _$DeviceTransferEvent {
  const DeviceTransferEvent._();

  const factory DeviceTransferEvent.restoreConnected() =
      DeviceTransferEvent_RestoreConnected;
  const factory DeviceTransferEvent.restoreStart() =
      DeviceTransferEvent_RestoreStart;
  const factory DeviceTransferEvent.restoreSucceed() =
      DeviceTransferEvent_RestoreSucceed;
  const factory DeviceTransferEvent.restoreFailed() =
      DeviceTransferEvent_RestoreFailed;
  const factory DeviceTransferEvent.backupServerCreated() =
      DeviceTransferEvent_BackupServerCreated;
  const factory DeviceTransferEvent.backupStart() =
      DeviceTransferEvent_BackupStart;
  const factory DeviceTransferEvent.backupSucceed() =
      DeviceTransferEvent_BackupSucceed;
  const factory DeviceTransferEvent.backupFailed() =
      DeviceTransferEvent_BackupFailed;
  const factory DeviceTransferEvent.restoreProgress(
    double field0,
  ) = DeviceTransferEvent_RestoreProgress;
  const factory DeviceTransferEvent.backupProgress(
    double field0,
  ) = DeviceTransferEvent_BackupProgress;
  const factory DeviceTransferEvent.restoreNetworkSpeed(
    double field0,
  ) = DeviceTransferEvent_RestoreNetworkSpeed;
  const factory DeviceTransferEvent.backupNetworkSpeed(
    double field0,
  ) = DeviceTransferEvent_BackupNetworkSpeed;
  const factory DeviceTransferEvent.backupRequestReceived() =
      DeviceTransferEvent_BackupRequestReceived;
  const factory DeviceTransferEvent.restoreRequestReceived() =
      DeviceTransferEvent_RestoreRequestReceived;
  const factory DeviceTransferEvent.connectionFailed(
    ConnectionFailedReason field0,
  ) = DeviceTransferEvent_ConnectionFailed;
}
