// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'frb_generated.dart';

part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`

@freezed
sealed class CoreError with _$CoreError implements FrbException {
  const CoreError._();

  const factory CoreError.unauthorized() = CoreError_Unauthorized;
  const factory CoreError.notFound() = CoreError_NotFound;
  const factory CoreError.cancelled() = CoreError_Cancelled;
  const factory CoreError.invalidArgument({
    required String message,
  }) = CoreError_InvalidArgument;
  const factory CoreError.other({
    required String message,
  }) = CoreError_Other;
}
