// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/account.dart';
import 'api/desktop.dart';
import 'api/logging.dart';
import 'api/login.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'third_party/mixin_desktop_core/core/device_transfer.dart';
import 'third_party/mixin_desktop_core/runtime.dart';
import 'third_party/mixin_desktop_core/runtime/logging.dart';
import 'third_party/mixin_desktop_core/runtime/model.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AccountHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AttachmentAccessPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ConversationAccessPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_DesktopHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LoginHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MessageAccessPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SettingsHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_StickerAccessPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UserAccessPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AccountHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    dynamic raw,
  );

  @protected
  AttachmentAccess
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    dynamic raw,
  );

  @protected
  ConversationAccess
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    dynamic raw,
  );

  @protected
  DesktopHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    dynamic raw,
  );

  @protected
  LoginHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    dynamic raw,
  );

  @protected
  MessageAccess
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    dynamic raw,
  );

  @protected
  SettingsHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    dynamic raw,
  );

  @protected
  StickerAccess
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    dynamic raw,
  );

  @protected
  UserAccess
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    dynamic raw,
  );

  @protected
  AccountHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    dynamic raw,
  );

  @protected
  AttachmentAccess
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    dynamic raw,
  );

  @protected
  ConversationAccess
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    dynamic raw,
  );

  @protected
  DesktopHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    dynamic raw,
  );

  @protected
  LoginHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    dynamic raw,
  );

  @protected
  MessageAccess
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    dynamic raw,
  );

  @protected
  SettingsHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    dynamic raw,
  );

  @protected
  StickerAccess
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    dynamic raw,
  );

  @protected
  UserAccess
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  AccountHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    dynamic raw,
  );

  @protected
  AttachmentAccess
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    dynamic raw,
  );

  @protected
  ConversationAccess
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    dynamic raw,
  );

  @protected
  DesktopHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    dynamic raw,
  );

  @protected
  LoginHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    dynamic raw,
  );

  @protected
  MessageAccess
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    dynamic raw,
  );

  @protected
  SettingsHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    dynamic raw,
  );

  @protected
  StickerAccess
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    dynamic raw,
  );

  @protected
  UserAccess
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<AccountProfile> dco_decode_StreamSink_account_profile_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<bool> dco_decode_StreamSink_bool_Sse(dynamic raw);

  @protected
  RustStreamSink<ConversationChangeEvent>
  dco_decode_StreamSink_conversation_change_event_Sse(dynamic raw);

  @protected
  RustStreamSink<DeviceTransferEvent>
  dco_decode_StreamSink_device_transfer_event_Sse(dynamic raw);

  @protected
  RustStreamSink<PlatformInt64> dco_decode_StreamSink_i_64_Sse(dynamic raw);

  @protected
  RustStreamSink<List<ConversationUnseenCount>>
  dco_decode_StreamSink_list_conversation_unseen_count_Sse(dynamic raw);

  @protected
  RustStreamSink<NotificationEvent>
  dco_decode_StreamSink_notification_event_Sse(dynamic raw);

  @protected
  RustStreamSink<String?> dco_decode_StreamSink_opt_String_Sse(dynamic raw);

  @protected
  RustStreamSink<BigInt> dco_decode_StreamSink_u_64_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountProfile dco_decode_account_profile(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccountHandle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    dynamic raw,
  );

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  McpSettingsItem dco_decode_box_autoadd_mcp_settings_item(dynamic raw);

  @protected
  MessageOrderInfoView dco_decode_box_autoadd_message_order_info_view(
    dynamic raw,
  );

  @protected
  PinMessagePreviewItem dco_decode_box_autoadd_pin_message_preview_item(
    dynamic raw,
  );

  @protected
  ProxySettingsItem dco_decode_box_autoadd_proxy_settings_item(dynamic raw);

  @protected
  StickerAlbumItem dco_decode_box_autoadd_sticker_album_item(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  UserProfileItem dco_decode_box_autoadd_user_profile_item(dynamic raw);

  @protected
  CircleItem dco_decode_circle_item(dynamic raw);

  @protected
  CodeResult dco_decode_code_result(dynamic raw);

  @protected
  ConnectionFailedReason dco_decode_connection_failed_reason(dynamic raw);

  @protected
  ConversationChangeEvent dco_decode_conversation_change_event(dynamic raw);

  @protected
  ConversationDetailItem dco_decode_conversation_detail_item(dynamic raw);

  @protected
  ConversationListData dco_decode_conversation_list_data(dynamic raw);

  @protected
  ConversationParticipantItem dco_decode_conversation_participant_item(
    dynamic raw,
  );

  @protected
  ConversationStorageUsage dco_decode_conversation_storage_usage(dynamic raw);

  @protected
  ConversationUnseenCount dco_decode_conversation_unseen_count(dynamic raw);

  @protected
  DeviceTransferCommand dco_decode_device_transfer_command(dynamic raw);

  @protected
  DeviceTransferEvent dco_decode_device_transfer_event(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GroupAvatar dco_decode_group_avatar(dynamic raw);

  @protected
  GroupConversationItem dco_decode_group_conversation_item(dynamic raw);

  @protected
  HttpResponseItem dco_decode_http_response_item(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageMessageView dco_decode_image_message_view(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CircleItem> dco_decode_list_circle_item(dynamic raw);

  @protected
  List<ConversationListData> dco_decode_list_conversation_list_data(
    dynamic raw,
  );

  @protected
  List<ConversationParticipantItem>
  dco_decode_list_conversation_participant_item(dynamic raw);

  @protected
  List<ConversationStorageUsage> dco_decode_list_conversation_storage_usage(
    dynamic raw,
  );

  @protected
  List<ConversationUnseenCount> dco_decode_list_conversation_unseen_count(
    dynamic raw,
  );

  @protected
  List<GroupAvatar> dco_decode_list_group_avatar(dynamic raw);

  @protected
  List<GroupConversationItem> dco_decode_list_group_conversation_item(
    dynamic raw,
  );

  @protected
  List<ImageMessageView> dco_decode_list_image_message_view(dynamic raw);

  @protected
  List<MessageListView> dco_decode_list_message_list_view(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProxyItem> dco_decode_list_proxy_item(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SharedAppItem> dco_decode_list_shared_app_item(dynamic raw);

  @protected
  List<StickerAlbumItem> dco_decode_list_sticker_album_item(dynamic raw);

  @protected
  List<StickerItem> dco_decode_list_sticker_item(dynamic raw);

  @protected
  List<StorageCategoryUsage> dco_decode_list_storage_category_usage(
    dynamic raw,
  );

  @protected
  List<UserProfileItem> dco_decode_list_user_profile_item(dynamic raw);

  @protected
  McpServerStatusItem dco_decode_mcp_server_status_item(dynamic raw);

  @protected
  McpSettingsItem dco_decode_mcp_settings_item(dynamic raw);

  @protected
  MessageListView dco_decode_message_list_view(dynamic raw);

  @protected
  MessageOrderInfoView dco_decode_message_order_info_view(dynamic raw);

  @protected
  NotificationEvent dco_decode_notification_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AccountHandle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    dynamic raw,
  );

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MessageOrderInfoView? dco_decode_opt_box_autoadd_message_order_info_view(
    dynamic raw,
  );

  @protected
  PinMessagePreviewItem? dco_decode_opt_box_autoadd_pin_message_preview_item(
    dynamic raw,
  );

  @protected
  StickerAlbumItem? dco_decode_opt_box_autoadd_sticker_album_item(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  UserProfileItem? dco_decode_opt_box_autoadd_user_profile_item(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PinMessagePreviewItem dco_decode_pin_message_preview_item(dynamic raw);

  @protected
  ProxyItem dco_decode_proxy_item(dynamic raw);

  @protected
  ProxySettingsItem dco_decode_proxy_settings_item(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SharedAppItem dco_decode_shared_app_item(dynamic raw);

  @protected
  SnapshotDetailItem dco_decode_snapshot_detail_item(dynamic raw);

  @protected
  StickerAlbumItem dco_decode_sticker_album_item(dynamic raw);

  @protected
  StickerDetailItem dco_decode_sticker_detail_item(dynamic raw);

  @protected
  StickerItem dco_decode_sticker_item(dynamic raw);

  @protected
  StorageCategoryUsage dco_decode_storage_category_usage(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserProfileItem dco_decode_user_profile_item(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AccountHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    SseDeserializer deserializer,
  );

  @protected
  AttachmentAccess
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    SseDeserializer deserializer,
  );

  @protected
  ConversationAccess
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    SseDeserializer deserializer,
  );

  @protected
  DesktopHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    SseDeserializer deserializer,
  );

  @protected
  LoginHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    SseDeserializer deserializer,
  );

  @protected
  MessageAccess
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    SseDeserializer deserializer,
  );

  @protected
  SettingsHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    SseDeserializer deserializer,
  );

  @protected
  StickerAccess
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    SseDeserializer deserializer,
  );

  @protected
  UserAccess
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    SseDeserializer deserializer,
  );

  @protected
  AccountHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    SseDeserializer deserializer,
  );

  @protected
  AttachmentAccess
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    SseDeserializer deserializer,
  );

  @protected
  ConversationAccess
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    SseDeserializer deserializer,
  );

  @protected
  DesktopHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    SseDeserializer deserializer,
  );

  @protected
  LoginHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    SseDeserializer deserializer,
  );

  @protected
  MessageAccess
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    SseDeserializer deserializer,
  );

  @protected
  SettingsHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    SseDeserializer deserializer,
  );

  @protected
  StickerAccess
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    SseDeserializer deserializer,
  );

  @protected
  UserAccess
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  AccountHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    SseDeserializer deserializer,
  );

  @protected
  AttachmentAccess
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    SseDeserializer deserializer,
  );

  @protected
  ConversationAccess
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    SseDeserializer deserializer,
  );

  @protected
  DesktopHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    SseDeserializer deserializer,
  );

  @protected
  LoginHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    SseDeserializer deserializer,
  );

  @protected
  MessageAccess
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    SseDeserializer deserializer,
  );

  @protected
  SettingsHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    SseDeserializer deserializer,
  );

  @protected
  StickerAccess
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    SseDeserializer deserializer,
  );

  @protected
  UserAccess
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AccountProfile> sse_decode_StreamSink_account_profile_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<bool> sse_decode_StreamSink_bool_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ConversationChangeEvent>
  sse_decode_StreamSink_conversation_change_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DeviceTransferEvent>
  sse_decode_StreamSink_device_transfer_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<PlatformInt64> sse_decode_StreamSink_i_64_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<ConversationUnseenCount>>
  sse_decode_StreamSink_list_conversation_unseen_count_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NotificationEvent>
  sse_decode_StreamSink_notification_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<String?> sse_decode_StreamSink_opt_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BigInt> sse_decode_StreamSink_u_64_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountProfile sse_decode_account_profile(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccountHandle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  McpSettingsItem sse_decode_box_autoadd_mcp_settings_item(
    SseDeserializer deserializer,
  );

  @protected
  MessageOrderInfoView sse_decode_box_autoadd_message_order_info_view(
    SseDeserializer deserializer,
  );

  @protected
  PinMessagePreviewItem sse_decode_box_autoadd_pin_message_preview_item(
    SseDeserializer deserializer,
  );

  @protected
  ProxySettingsItem sse_decode_box_autoadd_proxy_settings_item(
    SseDeserializer deserializer,
  );

  @protected
  StickerAlbumItem sse_decode_box_autoadd_sticker_album_item(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UserProfileItem sse_decode_box_autoadd_user_profile_item(
    SseDeserializer deserializer,
  );

  @protected
  CircleItem sse_decode_circle_item(SseDeserializer deserializer);

  @protected
  CodeResult sse_decode_code_result(SseDeserializer deserializer);

  @protected
  ConnectionFailedReason sse_decode_connection_failed_reason(
    SseDeserializer deserializer,
  );

  @protected
  ConversationChangeEvent sse_decode_conversation_change_event(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDetailItem sse_decode_conversation_detail_item(
    SseDeserializer deserializer,
  );

  @protected
  ConversationListData sse_decode_conversation_list_data(
    SseDeserializer deserializer,
  );

  @protected
  ConversationParticipantItem sse_decode_conversation_participant_item(
    SseDeserializer deserializer,
  );

  @protected
  ConversationStorageUsage sse_decode_conversation_storage_usage(
    SseDeserializer deserializer,
  );

  @protected
  ConversationUnseenCount sse_decode_conversation_unseen_count(
    SseDeserializer deserializer,
  );

  @protected
  DeviceTransferCommand sse_decode_device_transfer_command(
    SseDeserializer deserializer,
  );

  @protected
  DeviceTransferEvent sse_decode_device_transfer_event(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GroupAvatar sse_decode_group_avatar(SseDeserializer deserializer);

  @protected
  GroupConversationItem sse_decode_group_conversation_item(
    SseDeserializer deserializer,
  );

  @protected
  HttpResponseItem sse_decode_http_response_item(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageMessageView sse_decode_image_message_view(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CircleItem> sse_decode_list_circle_item(SseDeserializer deserializer);

  @protected
  List<ConversationListData> sse_decode_list_conversation_list_data(
    SseDeserializer deserializer,
  );

  @protected
  List<ConversationParticipantItem>
  sse_decode_list_conversation_participant_item(SseDeserializer deserializer);

  @protected
  List<ConversationStorageUsage> sse_decode_list_conversation_storage_usage(
    SseDeserializer deserializer,
  );

  @protected
  List<ConversationUnseenCount> sse_decode_list_conversation_unseen_count(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupAvatar> sse_decode_list_group_avatar(SseDeserializer deserializer);

  @protected
  List<GroupConversationItem> sse_decode_list_group_conversation_item(
    SseDeserializer deserializer,
  );

  @protected
  List<ImageMessageView> sse_decode_list_image_message_view(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageListView> sse_decode_list_message_list_view(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProxyItem> sse_decode_list_proxy_item(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SharedAppItem> sse_decode_list_shared_app_item(
    SseDeserializer deserializer,
  );

  @protected
  List<StickerAlbumItem> sse_decode_list_sticker_album_item(
    SseDeserializer deserializer,
  );

  @protected
  List<StickerItem> sse_decode_list_sticker_item(SseDeserializer deserializer);

  @protected
  List<StorageCategoryUsage> sse_decode_list_storage_category_usage(
    SseDeserializer deserializer,
  );

  @protected
  List<UserProfileItem> sse_decode_list_user_profile_item(
    SseDeserializer deserializer,
  );

  @protected
  McpServerStatusItem sse_decode_mcp_server_status_item(
    SseDeserializer deserializer,
  );

  @protected
  McpSettingsItem sse_decode_mcp_settings_item(SseDeserializer deserializer);

  @protected
  MessageListView sse_decode_message_list_view(SseDeserializer deserializer);

  @protected
  MessageOrderInfoView sse_decode_message_order_info_view(
    SseDeserializer deserializer,
  );

  @protected
  NotificationEvent sse_decode_notification_event(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AccountHandle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MessageOrderInfoView? sse_decode_opt_box_autoadd_message_order_info_view(
    SseDeserializer deserializer,
  );

  @protected
  PinMessagePreviewItem? sse_decode_opt_box_autoadd_pin_message_preview_item(
    SseDeserializer deserializer,
  );

  @protected
  StickerAlbumItem? sse_decode_opt_box_autoadd_sticker_album_item(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UserProfileItem? sse_decode_opt_box_autoadd_user_profile_item(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PinMessagePreviewItem sse_decode_pin_message_preview_item(
    SseDeserializer deserializer,
  );

  @protected
  ProxyItem sse_decode_proxy_item(SseDeserializer deserializer);

  @protected
  ProxySettingsItem sse_decode_proxy_settings_item(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SharedAppItem sse_decode_shared_app_item(SseDeserializer deserializer);

  @protected
  SnapshotDetailItem sse_decode_snapshot_detail_item(
    SseDeserializer deserializer,
  );

  @protected
  StickerAlbumItem sse_decode_sticker_album_item(SseDeserializer deserializer);

  @protected
  StickerDetailItem sse_decode_sticker_detail_item(
    SseDeserializer deserializer,
  );

  @protected
  StickerItem sse_decode_sticker_item(SseDeserializer deserializer);

  @protected
  StorageCategoryUsage sse_decode_storage_category_usage(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserProfileItem sse_decode_user_profile_item(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    AccountHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    AttachmentAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    ConversationAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    DesktopHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    LoginHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    MessageAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    SettingsHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    StickerAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    UserAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    AccountHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    AttachmentAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    ConversationAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    DesktopHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    LoginHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    MessageAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    SettingsHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    StickerAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    UserAccess self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    AccountHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    AttachmentAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    ConversationAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    DesktopHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    LoginHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    MessageAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    SettingsHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    StickerAccess self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    UserAccess self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_account_profile_Sse(
    RustStreamSink<AccountProfile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bool_Sse(
    RustStreamSink<bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_conversation_change_event_Sse(
    RustStreamSink<ConversationChangeEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_device_transfer_event_Sse(
    RustStreamSink<DeviceTransferEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_i_64_Sse(
    RustStreamSink<PlatformInt64> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_conversation_unseen_count_Sse(
    RustStreamSink<List<ConversationUnseenCount>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_notification_event_Sse(
    RustStreamSink<NotificationEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_opt_String_Sse(
    RustStreamSink<String?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_u_64_Sse(
    RustStreamSink<BigInt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_profile(
    AccountProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    AccountHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mcp_settings_item(
    McpSettingsItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_message_order_info_view(
    MessageOrderInfoView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pin_message_preview_item(
    PinMessagePreviewItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_proxy_settings_item(
    ProxySettingsItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sticker_album_item(
    StickerAlbumItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_profile_item(
    UserProfileItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_circle_item(CircleItem self, SseSerializer serializer);

  @protected
  void sse_encode_code_result(CodeResult self, SseSerializer serializer);

  @protected
  void sse_encode_connection_failed_reason(
    ConnectionFailedReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_change_event(
    ConversationChangeEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_detail_item(
    ConversationDetailItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_list_data(
    ConversationListData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_participant_item(
    ConversationParticipantItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_storage_usage(
    ConversationStorageUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_unseen_count(
    ConversationUnseenCount self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_transfer_command(
    DeviceTransferCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_transfer_event(
    DeviceTransferEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_group_avatar(GroupAvatar self, SseSerializer serializer);

  @protected
  void sse_encode_group_conversation_item(
    GroupConversationItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_http_response_item(
    HttpResponseItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_message_view(
    ImageMessageView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_circle_item(
    List<CircleItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conversation_list_data(
    List<ConversationListData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conversation_participant_item(
    List<ConversationParticipantItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conversation_storage_usage(
    List<ConversationStorageUsage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conversation_unseen_count(
    List<ConversationUnseenCount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_avatar(
    List<GroupAvatar> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_conversation_item(
    List<GroupConversationItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_image_message_view(
    List<ImageMessageView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_list_view(
    List<MessageListView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_item(
    List<ProxyItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_shared_app_item(
    List<SharedAppItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sticker_album_item(
    List<StickerAlbumItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sticker_item(
    List<StickerItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_storage_category_usage(
    List<StorageCategoryUsage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_profile_item(
    List<UserProfileItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mcp_server_status_item(
    McpServerStatusItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mcp_settings_item(
    McpSettingsItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_list_view(
    MessageListView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_order_info_view(
    MessageOrderInfoView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_event(
    NotificationEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    AccountHandle? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_message_order_info_view(
    MessageOrderInfoView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pin_message_preview_item(
    PinMessagePreviewItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sticker_album_item(
    StickerAlbumItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user_profile_item(
    UserProfileItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pin_message_preview_item(
    PinMessagePreviewItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_item(ProxyItem self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_settings_item(
    ProxySettingsItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shared_app_item(SharedAppItem self, SseSerializer serializer);

  @protected
  void sse_encode_snapshot_detail_item(
    SnapshotDetailItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sticker_album_item(
    StickerAlbumItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sticker_detail_item(
    StickerDetailItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sticker_item(StickerItem self, SseSerializer serializer);

  @protected
  void sse_encode_storage_category_usage(
    StorageCategoryUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile_item(
    UserProfileItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentAccess(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationAccess(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageAccess(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingsHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStickerAccess(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserAccess(
    int ptr,
  );
}
