// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/desktop.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiDesktopInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 236581877;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mixin_desktop_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiDesktopAccountHandleAccountId({required AccountHandle that});

  Future<List<CircleItem>> crateApiDesktopAccountHandleCircles({
    required AccountHandle that,
  });

  Stream<BigInt> crateApiDesktopAccountHandleConversationChanges({
    required AccountHandle that,
  });

  Future<PlatformInt64> crateApiDesktopAccountHandleConversationCount({
    required AccountHandle that,
    required String category,
    String? circleId,
    required String keyword,
    required bool unseenOnly,
  });

  Future<List<ConversationListItem>> crateApiDesktopAccountHandleConversations({
    required AccountHandle that,
    required String category,
    String? circleId,
    required String keyword,
    required bool unseenOnly,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  });

  Future<void> crateApiDesktopAccountHandleDeleteConversation({
    required AccountHandle that,
    required String conversationId,
  });

  Future<void> crateApiDesktopAccountHandleEditCircleConversation({
    required AccountHandle that,
    required String circleId,
    required String conversationId,
    required String ownerId,
    required bool isGroup,
    required bool add,
  });

  AccountProfile crateApiDesktopAccountHandleProfile({
    required AccountHandle that,
  });

  Future<void> crateApiDesktopAccountHandleSetConversationMuted({
    required AccountHandle that,
    required String conversationId,
    required String ownerId,
    required String category,
    required PlatformInt64 durationSeconds,
  });

  Future<void> crateApiDesktopAccountHandleSetConversationPinned({
    required AccountHandle that,
    required String conversationId,
    required bool pinned,
  });

  Future<void> crateApiDesktopAccountHandleShutdown({
    required AccountHandle that,
  });

  Future<LoginHandle> crateApiDesktopDesktopHandleBeginLogin({
    required DesktopHandle that,
  });

  Future<AccountHandle?> crateApiDesktopDesktopHandleRestoreAccount({
    required DesktopHandle that,
  });

  String crateApiDesktopLoginHandleAuthUrl({required LoginHandle that});

  Future<AccountHandle?> crateApiDesktopLoginHandlePoll({
    required LoginHandle that,
  });

  Future<void> crateApiDesktopInitApp();

  Future<DesktopHandle> crateApiDesktopOpenDesktop();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AccountHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AccountHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AccountHandlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_DesktopHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_DesktopHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_DesktopHandlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LoginHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LoginHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LoginHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiDesktopAccountHandleAccountId({required AccountHandle that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDesktopAccountHandleAccountIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopAccountHandleAccountIdConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_account_id",
        argNames: ["that"],
      );

  @override
  Future<List<CircleItem>> crateApiDesktopAccountHandleCircles({
    required AccountHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_circle_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopAccountHandleCirclesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopAccountHandleCirclesConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_circles",
        argNames: ["that"],
      );

  @override
  Stream<BigInt> crateApiDesktopAccountHandleConversationChanges({
    required AccountHandle that,
  }) {
    final sink = RustStreamSink<BigInt>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
              that,
              serializer,
            );
            sse_encode_StreamSink_u_64_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiDesktopAccountHandleConversationChangesConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDesktopAccountHandleConversationChangesConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_conversation_changes",
        argNames: ["that", "sink"],
      );

  @override
  Future<PlatformInt64> crateApiDesktopAccountHandleConversationCount({
    required AccountHandle that,
    required String category,
    String? circleId,
    required String keyword,
    required bool unseenOnly,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            that,
            serializer,
          );
          sse_encode_String(category, serializer);
          sse_encode_opt_String(circleId, serializer);
          sse_encode_String(keyword, serializer);
          sse_encode_bool(unseenOnly, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopAccountHandleConversationCountConstMeta,
        argValues: [that, category, circleId, keyword, unseenOnly],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopAccountHandleConversationCountConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_conversation_count",
        argNames: ["that", "category", "circleId", "keyword", "unseenOnly"],
      );

  @override
  Future<List<ConversationListItem>> crateApiDesktopAccountHandleConversations({
    required AccountHandle that,
    required String category,
    String? circleId,
    required String keyword,
    required bool unseenOnly,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            that,
            serializer,
          );
          sse_encode_String(category, serializer);
          sse_encode_opt_String(circleId, serializer);
          sse_encode_String(keyword, serializer);
          sse_encode_bool(unseenOnly, serializer);
          sse_encode_i_64(limit, serializer);
          sse_encode_i_64(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_conversation_list_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopAccountHandleConversationsConstMeta,
        argValues: [
          that,
          category,
          circleId,
          keyword,
          unseenOnly,
          limit,
          offset,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopAccountHandleConversationsConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_conversations",
        argNames: [
          "that",
          "category",
          "circleId",
          "keyword",
          "unseenOnly",
          "limit",
          "offset",
        ],
      );

  @override
  Future<void> crateApiDesktopAccountHandleDeleteConversation({
    required AccountHandle that,
    required String conversationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            that,
            serializer,
          );
          sse_encode_String(conversationId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopAccountHandleDeleteConversationConstMeta,
        argValues: [that, conversationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopAccountHandleDeleteConversationConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_delete_conversation",
        argNames: ["that", "conversationId"],
      );

  @override
  Future<void> crateApiDesktopAccountHandleEditCircleConversation({
    required AccountHandle that,
    required String circleId,
    required String conversationId,
    required String ownerId,
    required bool isGroup,
    required bool add,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            that,
            serializer,
          );
          sse_encode_String(circleId, serializer);
          sse_encode_String(conversationId, serializer);
          sse_encode_String(ownerId, serializer);
          sse_encode_bool(isGroup, serializer);
          sse_encode_bool(add, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopAccountHandleEditCircleConversationConstMeta,
        argValues: [that, circleId, conversationId, ownerId, isGroup, add],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDesktopAccountHandleEditCircleConversationConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_edit_circle_conversation",
        argNames: [
          "that",
          "circleId",
          "conversationId",
          "ownerId",
          "isGroup",
          "add",
        ],
      );

  @override
  AccountProfile crateApiDesktopAccountHandleProfile({
    required AccountHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_profile,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDesktopAccountHandleProfileConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopAccountHandleProfileConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_profile",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiDesktopAccountHandleSetConversationMuted({
    required AccountHandle that,
    required String conversationId,
    required String ownerId,
    required String category,
    required PlatformInt64 durationSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            that,
            serializer,
          );
          sse_encode_String(conversationId, serializer);
          sse_encode_String(ownerId, serializer);
          sse_encode_String(category, serializer);
          sse_encode_i_64(durationSeconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopAccountHandleSetConversationMutedConstMeta,
        argValues: [that, conversationId, ownerId, category, durationSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDesktopAccountHandleSetConversationMutedConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_set_conversation_muted",
        argNames: [
          "that",
          "conversationId",
          "ownerId",
          "category",
          "durationSeconds",
        ],
      );

  @override
  Future<void> crateApiDesktopAccountHandleSetConversationPinned({
    required AccountHandle that,
    required String conversationId,
    required bool pinned,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            that,
            serializer,
          );
          sse_encode_String(conversationId, serializer);
          sse_encode_bool(pinned, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopAccountHandleSetConversationPinnedConstMeta,
        argValues: [that, conversationId, pinned],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDesktopAccountHandleSetConversationPinnedConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_set_conversation_pinned",
        argNames: ["that", "conversationId", "pinned"],
      );

  @override
  Future<void> crateApiDesktopAccountHandleShutdown({
    required AccountHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDesktopAccountHandleShutdownConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopAccountHandleShutdownConstMeta =>
      const TaskConstMeta(
        debugName: "AccountHandle_shutdown",
        argNames: ["that"],
      );

  @override
  Future<LoginHandle> crateApiDesktopDesktopHandleBeginLogin({
    required DesktopHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopDesktopHandleBeginLoginConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopDesktopHandleBeginLoginConstMeta =>
      const TaskConstMeta(
        debugName: "DesktopHandle_begin_login",
        argNames: ["that"],
      );

  @override
  Future<AccountHandle?> crateApiDesktopDesktopHandleRestoreAccount({
    required DesktopHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopDesktopHandleRestoreAccountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopDesktopHandleRestoreAccountConstMeta =>
      const TaskConstMeta(
        debugName: "DesktopHandle_restore_account",
        argNames: ["that"],
      );

  @override
  String crateApiDesktopLoginHandleAuthUrl({required LoginHandle that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDesktopLoginHandleAuthUrlConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopLoginHandleAuthUrlConstMeta =>
      const TaskConstMeta(
        debugName: "LoginHandle_auth_url",
        argNames: ["that"],
      );

  @override
  Future<AccountHandle?> crateApiDesktopLoginHandlePoll({
    required LoginHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopLoginHandlePollConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopLoginHandlePollConstMeta =>
      const TaskConstMeta(debugName: "LoginHandle_poll", argNames: ["that"]);

  @override
  Future<void> crateApiDesktopInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDesktopInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<DesktopHandle> crateApiDesktopOpenDesktop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDesktopOpenDesktopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopOpenDesktopConstMeta =>
      const TaskConstMeta(debugName: "open_desktop", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AccountHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AccountHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_DesktopHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_DesktopHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LoginHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LoginHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  AccountHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AccountHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DesktopHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DesktopHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoginHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoginHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AccountHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AccountHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DesktopHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DesktopHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoginHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoginHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AccountHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AccountHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DesktopHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DesktopHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LoginHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoginHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<BigInt> dco_decode_StreamSink_u_64_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountProfile dco_decode_account_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AccountProfile(
      userId: dco_decode_String(arr[0]),
      fullName: dco_decode_String(arr[1]),
      avatarUrl: dco_decode_String(arr[2]),
      identityNumber: dco_decode_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AccountHandle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
      raw,
    );
  }

  @protected
  CircleItem dco_decode_circle_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CircleItem(
      circleId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  ConversationListItem dco_decode_conversation_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 23)
      throw Exception('unexpected arr length: expect 23 but see ${arr.length}');
    return ConversationListItem(
      conversationId: dco_decode_String(arr[0]),
      ownerId: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      avatarUrl: dco_decode_String(arr[3]),
      category: dco_decode_String(arr[4]),
      draft: dco_decode_String(arr[5]),
      status: dco_decode_i_32(arr[6]),
      lastMessage: dco_decode_String(arr[7]),
      lastMessageCategory: dco_decode_opt_String(arr[8]),
      lastMessageStatus: dco_decode_opt_String(arr[9]),
      lastMessageSenderId: dco_decode_opt_String(arr[10]),
      lastMessageSenderName: dco_decode_opt_String(arr[11]),
      updatedAtMillis: dco_decode_i_64(arr[12]),
      unseenCount: dco_decode_i_64(arr[13]),
      mentionCount: dco_decode_i_64(arr[14]),
      isMuted: dco_decode_bool(arr[15]),
      isVerified: dco_decode_bool(arr[16]),
      isBot: dco_decode_bool(arr[17]),
      isPinned: dco_decode_bool(arr[18]),
      relationship: dco_decode_String(arr[19]),
      identityNumber: dco_decode_String(arr[20]),
      circleIds: dco_decode_list_String(arr[21]),
      groupAvatars: dco_decode_list_group_avatar(arr[22]),
    );
  }

  @protected
  GroupAvatar dco_decode_group_avatar(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GroupAvatar(
      userId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      avatarUrl: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CircleItem> dco_decode_list_circle_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_circle_item).toList();
  }

  @protected
  List<ConversationListItem> dco_decode_list_conversation_list_item(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_conversation_list_item)
        .toList();
  }

  @protected
  List<GroupAvatar> dco_decode_list_group_avatar(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_group_avatar).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AccountHandle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
            raw,
          );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  AccountHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AccountHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  DesktopHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DesktopHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LoginHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoginHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AccountHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AccountHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  DesktopHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DesktopHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LoginHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoginHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AccountHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AccountHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  DesktopHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DesktopHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LoginHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LoginHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<BigInt> sse_decode_StreamSink_u_64_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountProfile sse_decode_account_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_fullName = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_String(deserializer);
    var var_identityNumber = sse_decode_String(deserializer);
    return AccountProfile(
      userId: var_userId,
      fullName: var_fullName,
      avatarUrl: var_avatarUrl,
      identityNumber: var_identityNumber,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AccountHandle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
      deserializer,
    ));
  }

  @protected
  CircleItem sse_decode_circle_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_circleId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return CircleItem(circleId: var_circleId, name: var_name);
  }

  @protected
  ConversationListItem sse_decode_conversation_list_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_conversationId = sse_decode_String(deserializer);
    var var_ownerId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_draft = sse_decode_String(deserializer);
    var var_status = sse_decode_i_32(deserializer);
    var var_lastMessage = sse_decode_String(deserializer);
    var var_lastMessageCategory = sse_decode_opt_String(deserializer);
    var var_lastMessageStatus = sse_decode_opt_String(deserializer);
    var var_lastMessageSenderId = sse_decode_opt_String(deserializer);
    var var_lastMessageSenderName = sse_decode_opt_String(deserializer);
    var var_updatedAtMillis = sse_decode_i_64(deserializer);
    var var_unseenCount = sse_decode_i_64(deserializer);
    var var_mentionCount = sse_decode_i_64(deserializer);
    var var_isMuted = sse_decode_bool(deserializer);
    var var_isVerified = sse_decode_bool(deserializer);
    var var_isBot = sse_decode_bool(deserializer);
    var var_isPinned = sse_decode_bool(deserializer);
    var var_relationship = sse_decode_String(deserializer);
    var var_identityNumber = sse_decode_String(deserializer);
    var var_circleIds = sse_decode_list_String(deserializer);
    var var_groupAvatars = sse_decode_list_group_avatar(deserializer);
    return ConversationListItem(
      conversationId: var_conversationId,
      ownerId: var_ownerId,
      name: var_name,
      avatarUrl: var_avatarUrl,
      category: var_category,
      draft: var_draft,
      status: var_status,
      lastMessage: var_lastMessage,
      lastMessageCategory: var_lastMessageCategory,
      lastMessageStatus: var_lastMessageStatus,
      lastMessageSenderId: var_lastMessageSenderId,
      lastMessageSenderName: var_lastMessageSenderName,
      updatedAtMillis: var_updatedAtMillis,
      unseenCount: var_unseenCount,
      mentionCount: var_mentionCount,
      isMuted: var_isMuted,
      isVerified: var_isVerified,
      isBot: var_isBot,
      isPinned: var_isPinned,
      relationship: var_relationship,
      identityNumber: var_identityNumber,
      circleIds: var_circleIds,
      groupAvatars: var_groupAvatars,
    );
  }

  @protected
  GroupAvatar sse_decode_group_avatar(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_String(deserializer);
    return GroupAvatar(
      userId: var_userId,
      name: var_name,
      avatarUrl: var_avatarUrl,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CircleItem> sse_decode_list_circle_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CircleItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_circle_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConversationListItem> sse_decode_list_conversation_list_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConversationListItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversation_list_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<GroupAvatar> sse_decode_list_group_avatar(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GroupAvatar>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_group_avatar(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AccountHandle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    AccountHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AccountHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    DesktopHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DesktopHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    LoginHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LoginHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    AccountHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AccountHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    DesktopHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DesktopHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    LoginHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LoginHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    AccountHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AccountHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDesktopHandle(
    DesktopHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DesktopHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLoginHandle(
    LoginHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LoginHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_u_64_Sse(
    RustStreamSink<BigInt> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_profile(
    AccountProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.fullName, serializer);
    sse_encode_String(self.avatarUrl, serializer);
    sse_encode_String(self.identityNumber, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    AccountHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_circle_item(CircleItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.circleId, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_conversation_list_item(
    ConversationListItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.conversationId, serializer);
    sse_encode_String(self.ownerId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.avatarUrl, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.draft, serializer);
    sse_encode_i_32(self.status, serializer);
    sse_encode_String(self.lastMessage, serializer);
    sse_encode_opt_String(self.lastMessageCategory, serializer);
    sse_encode_opt_String(self.lastMessageStatus, serializer);
    sse_encode_opt_String(self.lastMessageSenderId, serializer);
    sse_encode_opt_String(self.lastMessageSenderName, serializer);
    sse_encode_i_64(self.updatedAtMillis, serializer);
    sse_encode_i_64(self.unseenCount, serializer);
    sse_encode_i_64(self.mentionCount, serializer);
    sse_encode_bool(self.isMuted, serializer);
    sse_encode_bool(self.isVerified, serializer);
    sse_encode_bool(self.isBot, serializer);
    sse_encode_bool(self.isPinned, serializer);
    sse_encode_String(self.relationship, serializer);
    sse_encode_String(self.identityNumber, serializer);
    sse_encode_list_String(self.circleIds, serializer);
    sse_encode_list_group_avatar(self.groupAvatars, serializer);
  }

  @protected
  void sse_encode_group_avatar(GroupAvatar self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.avatarUrl, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_circle_item(
    List<CircleItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_circle_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conversation_list_item(
    List<ConversationListItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversation_list_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_group_avatar(
    List<GroupAvatar> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_group_avatar(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
    AccountHandle? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAccountHandle(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class AccountHandleImpl extends RustOpaque implements AccountHandle {
  // Not to be used by end users
  AccountHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AccountHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AccountHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AccountHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AccountHandlePtr,
  );

  String accountId() =>
      RustLib.instance.api.crateApiDesktopAccountHandleAccountId(that: this);

  Future<List<CircleItem>> circles() =>
      RustLib.instance.api.crateApiDesktopAccountHandleCircles(that: this);

  Stream<BigInt> conversationChanges() => RustLib.instance.api
      .crateApiDesktopAccountHandleConversationChanges(that: this);

  Future<PlatformInt64> conversationCount({
    required String category,
    String? circleId,
    required String keyword,
    required bool unseenOnly,
  }) => RustLib.instance.api.crateApiDesktopAccountHandleConversationCount(
    that: this,
    category: category,
    circleId: circleId,
    keyword: keyword,
    unseenOnly: unseenOnly,
  );

  Future<List<ConversationListItem>> conversations({
    required String category,
    String? circleId,
    required String keyword,
    required bool unseenOnly,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  }) => RustLib.instance.api.crateApiDesktopAccountHandleConversations(
    that: this,
    category: category,
    circleId: circleId,
    keyword: keyword,
    unseenOnly: unseenOnly,
    limit: limit,
    offset: offset,
  );

  Future<void> deleteConversation({required String conversationId}) =>
      RustLib.instance.api.crateApiDesktopAccountHandleDeleteConversation(
        that: this,
        conversationId: conversationId,
      );

  Future<void> editCircleConversation({
    required String circleId,
    required String conversationId,
    required String ownerId,
    required bool isGroup,
    required bool add,
  }) => RustLib.instance.api.crateApiDesktopAccountHandleEditCircleConversation(
    that: this,
    circleId: circleId,
    conversationId: conversationId,
    ownerId: ownerId,
    isGroup: isGroup,
    add: add,
  );

  AccountProfile profile() =>
      RustLib.instance.api.crateApiDesktopAccountHandleProfile(that: this);

  Future<void> setConversationMuted({
    required String conversationId,
    required String ownerId,
    required String category,
    required PlatformInt64 durationSeconds,
  }) => RustLib.instance.api.crateApiDesktopAccountHandleSetConversationMuted(
    that: this,
    conversationId: conversationId,
    ownerId: ownerId,
    category: category,
    durationSeconds: durationSeconds,
  );

  Future<void> setConversationPinned({
    required String conversationId,
    required bool pinned,
  }) => RustLib.instance.api.crateApiDesktopAccountHandleSetConversationPinned(
    that: this,
    conversationId: conversationId,
    pinned: pinned,
  );

  Future<void> shutdown() =>
      RustLib.instance.api.crateApiDesktopAccountHandleShutdown(that: this);
}

@sealed
class DesktopHandleImpl extends RustOpaque implements DesktopHandle {
  // Not to be used by end users
  DesktopHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  DesktopHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_DesktopHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_DesktopHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_DesktopHandlePtr,
  );

  Future<LoginHandle> beginLogin() =>
      RustLib.instance.api.crateApiDesktopDesktopHandleBeginLogin(that: this);

  Future<AccountHandle?> restoreAccount() => RustLib.instance.api
      .crateApiDesktopDesktopHandleRestoreAccount(that: this);
}

@sealed
class LoginHandleImpl extends RustOpaque implements LoginHandle {
  // Not to be used by end users
  LoginHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LoginHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LoginHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LoginHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LoginHandlePtr,
  );

  String authUrl() =>
      RustLib.instance.api.crateApiDesktopLoginHandleAuthUrl(that: this);

  Future<AccountHandle?> poll() =>
      RustLib.instance.api.crateApiDesktopLoginHandlePoll(that: this);
}
