[package]
name = "mixin_desktop_flutter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
futures = "0.3"
log = "0.4"
mixin_desktop_api = { path = "../../mixin_desktop_api" }
mixin_desktop_core = { path = "../../mixin_desktop_core" }
thiserror = "2"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
