// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/mixin_desktop_core/runtime.dart';
import '../third_party/mixin_desktop_core/runtime/model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_profile`, `forward_conversation_changes`, `forward_message_changes`, `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AccountHandle>>
abstract class AccountHandle implements RustOpaqueInterface {
  Stream<String> accountHealth();

  String accountId();

  AttachmentAccess attachment();

  Future<void> clearConversationStorage({
    required String conversationId,
    required List<String> categories,
  });

  Stream<bool> connectionStatus();

  ConversationAccess conversation();

  Stream<ConversationChangeEvent> conversationChanges();

  Future<List<StorageCategoryUsage>> conversationStorageUsage({
    required String conversationId,
  });

  Stream<NotificationEvent> desktopNotificationEvents();

  Future<void> deviceTransferCommand({required String command});

  Stream<String> deviceTransferEvents();

  double downloadProgress({required String messageId});

  String mediaDirectory();

  MessageAccess message();

  Stream<BigInt> messageChanges();

  AccountProfile profile();

  Stream<AccountProfile> profileChanges();

  Future<void> refreshAccountHealth();

  Future<AccountProfile> refreshProfile();

  void retryConnection();

  Future<SnapshotDetailItem> safeSnapshotById({required String snapshotId});

  Future<void> shutdown();

  Future<void> signOut();

  Future<SnapshotDetailItem> snapshotById({required String snapshotId});

  Future<SnapshotDetailItem> snapshotByTrace({required String traceId});

  StickerAccess sticker();

  Future<List<ConversationStorageUsage>> storageUsage();

  Stream<List<ConversationUnseenCount>> unseenCountChanges();

  Stream<PlatformInt64> unseenMessageCountChanges();

  Future<AccountProfile> updateProfile({
    required String fullName,
    required String biography,
  });

  UserAccess user();
}
