// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import '../third_party/mixin_desktop_api/model.dart';
import 'account.dart';
import 'login.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<DesktopHandle> openDesktop() =>
    RustLib.instance.api.crateApiDesktopOpenDesktop();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DesktopHandle>>
abstract class DesktopHandle implements RustOpaqueInterface {
  Future<void> abortSavedLogin();

  Future<LoginHandle> beginLogin();

  Future<HttpResponseItem> httpRequest({
    required String method,
    required String url,
    required Map<String, String> headers,
    Uint8List? body,
    BigInt? timeoutMillis,
    BigInt? maxResponseBytes,
  });

  Future<void> recreateAccountDatabase();

  Future<AccountHandle> restoreAccount();

  SettingsHandle get settings;
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SettingsHandle>>
abstract class SettingsHandle implements RustOpaqueInterface {
  Future<bool> fileAutoDownload();

  Future<McpServerStatusItem> mcpServerStatus();

  Future<McpSettingsItem> mcpSettings();

  Future<bool> photoAutoDownload();

  Future<ProxySettingsItem> proxySettings();

  Future<void> setFileAutoDownload({required bool value});

  Future<void> setPhotoAutoDownload({required bool value});

  Future<void> setProxySettings({required ProxySettingsItem settings});

  Future<void> setSetting({required String key, String? value});

  Future<void> setVideoAutoDownload({required bool value});

  Future<String?> setting({required String key});

  Stream<bool> subscribeFileAutoDownload();

  Stream<bool> subscribePhotoAutoDownload();

  Stream<String?> subscribeSetting({required String key});

  Stream<bool> subscribeVideoAutoDownload();

  Future<McpServerStatusItem> updateMcpSettings({
    required McpSettingsItem settings,
  });

  Future<bool> videoAutoDownload();
}
