// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `desktop_platform`

Future<DesktopHandle> openDesktop() =>
    RustLib.instance.api.crateApiDesktopOpenDesktop();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AccountHandle>>
abstract class AccountHandle implements RustOpaqueInterface {
  String accountId();

  Future<List<CircleItem>> circles();

  Stream<BigInt> conversationChanges();

  Future<PlatformInt64> conversationCount({
    required String category,
    String? circleId,
    required String keyword,
    required bool unseenOnly,
  });

  Future<List<ConversationListItem>> conversations({
    required String category,
    String? circleId,
    required String keyword,
    required bool unseenOnly,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  });

  Future<void> deleteConversation({required String conversationId});

  Future<void> editCircleConversation({
    required String circleId,
    required String conversationId,
    required String ownerId,
    required bool isGroup,
    required bool add,
  });

  AccountProfile profile();

  Future<void> setConversationMuted({
    required String conversationId,
    required String ownerId,
    required String category,
    required PlatformInt64 durationSeconds,
  });

  Future<void> setConversationPinned({
    required String conversationId,
    required bool pinned,
  });

  Future<void> shutdown();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DesktopHandle>>
abstract class DesktopHandle implements RustOpaqueInterface {
  Future<LoginHandle> beginLogin();

  Future<AccountHandle?> restoreAccount();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LoginHandle>>
abstract class LoginHandle implements RustOpaqueInterface {
  String authUrl();

  Future<AccountHandle?> poll();
}

class AccountProfile {
  final String userId;
  final String fullName;
  final String avatarUrl;
  final String identityNumber;

  const AccountProfile({
    required this.userId,
    required this.fullName,
    required this.avatarUrl,
    required this.identityNumber,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      fullName.hashCode ^
      avatarUrl.hashCode ^
      identityNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountProfile &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          fullName == other.fullName &&
          avatarUrl == other.avatarUrl &&
          identityNumber == other.identityNumber;
}

class CircleItem {
  final String circleId;
  final String name;

  const CircleItem({required this.circleId, required this.name});

  @override
  int get hashCode => circleId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CircleItem &&
          runtimeType == other.runtimeType &&
          circleId == other.circleId &&
          name == other.name;
}

class ConversationListItem {
  final String conversationId;
  final String ownerId;
  final String name;
  final String avatarUrl;
  final String category;
  final String draft;
  final int status;
  final String lastMessage;
  final String? lastMessageCategory;
  final String? lastMessageStatus;
  final String? lastMessageSenderId;
  final String? lastMessageSenderName;
  final PlatformInt64 updatedAtMillis;
  final PlatformInt64 unseenCount;
  final PlatformInt64 mentionCount;
  final bool isMuted;
  final bool isVerified;
  final bool isBot;
  final bool isPinned;
  final String relationship;
  final String identityNumber;
  final List<String> circleIds;
  final List<GroupAvatar> groupAvatars;

  const ConversationListItem({
    required this.conversationId,
    required this.ownerId,
    required this.name,
    required this.avatarUrl,
    required this.category,
    required this.draft,
    required this.status,
    required this.lastMessage,
    this.lastMessageCategory,
    this.lastMessageStatus,
    this.lastMessageSenderId,
    this.lastMessageSenderName,
    required this.updatedAtMillis,
    required this.unseenCount,
    required this.mentionCount,
    required this.isMuted,
    required this.isVerified,
    required this.isBot,
    required this.isPinned,
    required this.relationship,
    required this.identityNumber,
    required this.circleIds,
    required this.groupAvatars,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^
      ownerId.hashCode ^
      name.hashCode ^
      avatarUrl.hashCode ^
      category.hashCode ^
      draft.hashCode ^
      status.hashCode ^
      lastMessage.hashCode ^
      lastMessageCategory.hashCode ^
      lastMessageStatus.hashCode ^
      lastMessageSenderId.hashCode ^
      lastMessageSenderName.hashCode ^
      updatedAtMillis.hashCode ^
      unseenCount.hashCode ^
      mentionCount.hashCode ^
      isMuted.hashCode ^
      isVerified.hashCode ^
      isBot.hashCode ^
      isPinned.hashCode ^
      relationship.hashCode ^
      identityNumber.hashCode ^
      circleIds.hashCode ^
      groupAvatars.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationListItem &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          ownerId == other.ownerId &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          category == other.category &&
          draft == other.draft &&
          status == other.status &&
          lastMessage == other.lastMessage &&
          lastMessageCategory == other.lastMessageCategory &&
          lastMessageStatus == other.lastMessageStatus &&
          lastMessageSenderId == other.lastMessageSenderId &&
          lastMessageSenderName == other.lastMessageSenderName &&
          updatedAtMillis == other.updatedAtMillis &&
          unseenCount == other.unseenCount &&
          mentionCount == other.mentionCount &&
          isMuted == other.isMuted &&
          isVerified == other.isVerified &&
          isBot == other.isBot &&
          isPinned == other.isPinned &&
          relationship == other.relationship &&
          identityNumber == other.identityNumber &&
          circleIds == other.circleIds &&
          groupAvatars == other.groupAvatars;
}

class GroupAvatar {
  final String userId;
  final String name;
  final String avatarUrl;

  const GroupAvatar({
    required this.userId,
    required this.name,
    required this.avatarUrl,
  });

  @override
  int get hashCode => userId.hashCode ^ name.hashCode ^ avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupAvatar &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          avatarUrl == other.avatarUrl;
}
