// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'account.dart';

// These functions are ignored because they are not marked as `pub`: `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LoginHandle>>
abstract class LoginHandle implements RustOpaqueInterface {
  String authUrl();

  void cancel();

  Future<AccountHandle> wait();
}
