// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'media.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MediaHandle>>
abstract class MediaHandle implements RustOpaqueInterface {
  Stream<MediaPlaybackEvent> audioPlaybackEvents();

  MediaPlaybackSnapshot audioPlaybackSnapshot();

  Future<void> cancelVoiceRecording();

  Future<void> pauseAudio();

  Future<void> playAudio({
    required List<MediaAudioItem> playlist,
    required BigInt startIndex,
  });

  Future<void> resumeAudio();

  void seekAudio({required BigInt positionMillis});

  Future<void> setAudioSpeed({required double speed});

  Future<void> startVoiceRecording();

  void stopAudio();

  Future<MediaVoiceRecording> stopVoiceRecording();

  Stream<MediaRecorderEvent> voiceRecorderEvents();

  MediaRecorderSnapshot voiceRecorderSnapshot();
}

class MediaAudioItem {
  final String id;
  final String path;
  final BigInt durationMillis;

  const MediaAudioItem({
    required this.id,
    required this.path,
    required this.durationMillis,
  });

  @override
  int get hashCode => id.hashCode ^ path.hashCode ^ durationMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaAudioItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          durationMillis == other.durationMillis;
}

@freezed
sealed class MediaPlaybackEvent with _$MediaPlaybackEvent {
  const MediaPlaybackEvent._();

  const factory MediaPlaybackEvent.changed({
    required MediaPlaybackSnapshot snapshot,
  }) = MediaPlaybackEvent_Changed;
  const factory MediaPlaybackEvent.finished({
    required String id,
  }) = MediaPlaybackEvent_Finished;
  const factory MediaPlaybackEvent.failed({
    String? id,
    required String message,
  }) = MediaPlaybackEvent_Failed;
}

class MediaPlaybackSnapshot {
  final MediaPlaybackStatus status;
  final MediaAudioItem? item;
  final BigInt positionMillis;
  final BigInt durationMillis;
  final double speed;

  const MediaPlaybackSnapshot({
    required this.status,
    this.item,
    required this.positionMillis,
    required this.durationMillis,
    required this.speed,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      item.hashCode ^
      positionMillis.hashCode ^
      durationMillis.hashCode ^
      speed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaPlaybackSnapshot &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          item == other.item &&
          positionMillis == other.positionMillis &&
          durationMillis == other.durationMillis &&
          speed == other.speed;
}

enum MediaPlaybackStatus {
  idle,
  playing,
  paused,
}

@freezed
sealed class MediaRecorderEvent with _$MediaRecorderEvent {
  const MediaRecorderEvent._();

  const factory MediaRecorderEvent.changed({
    required MediaRecorderSnapshot snapshot,
  }) = MediaRecorderEvent_Changed;
  const factory MediaRecorderEvent.failed({
    required String message,
  }) = MediaRecorderEvent_Failed;
}

class MediaRecorderSnapshot {
  final MediaRecorderStatus status;
  final MediaVoiceRecording? recording;

  const MediaRecorderSnapshot({
    required this.status,
    this.recording,
  });

  @override
  int get hashCode => status.hashCode ^ recording.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaRecorderSnapshot &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          recording == other.recording;
}

enum MediaRecorderStatus {
  idle,
  recording,
  recorded,
}

class MediaVoiceRecording {
  final String path;
  final BigInt durationMillis;
  final Uint8List waveform;

  const MediaVoiceRecording({
    required this.path,
    required this.durationMillis,
    required this.waveform,
  });

  @override
  int get hashCode =>
      path.hashCode ^ durationMillis.hashCode ^ waveform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaVoiceRecording &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          durationMillis == other.durationMillis &&
          waveform == other.waveform;
}
